resources:
  - name: ankul_sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: ankul_test_pipeline
    setup:
      runtime: host
    steps:
      - name: ankul_test_bash_step
        type: bash
        setup:
          runtime: 
            type: host
        triggeredBy:
          resources:
            - ankul_sample_node 
        execution:
          onExecute:
            - echo "First run....."
            - echo "executing test bash step..."
