resources:
  - name: ankul_sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: github_int
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_with_image_runtime
    setup:
      runtime:
        type: image
        image:
          auto:
            language: nodeJs
            versions:
              - 11.10.0  
    steps:
       - name: step_without_runtime_1
         type: bash
         requires:
           resources:
             - ankul_sample_node
         execution:
           onExecute:
             - echo hello_world!

       - name: step_with_image_runtime_1
         type: bash
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodeJs
                 versions:
                   - 8.15.0
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!

       - name: step_with_custom_runtime_1
         type: bash
         setup:
           runtime:
             type: image
             image:
               custom:
                 name: drydock/u16ruball
                 tag: master
                 
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!

  - name: pipeline_with_custom_runtime
    setup:
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16javall
            tag: master 
    steps:
       - name: step_without_runtime_2
         type: bash
         requires:
           resources:
             - ankul_sample_node
         execution:
           onExecute:
             - echo hello_world!

       - name: step_with_image_runtime_2
         type: bash
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodeJs
                 versions:
                   - 8.15.0
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!

       - name: step_with_custom_runtime_2
         type: bash
         setup:
           runtime:
             type: image
             image:
               custom:
                 name: drydock/u16phpall
                 tag: master
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!                 

  - name: pipeline_default_auto_test
    steps:
       - name: test_bash_step
         type: bash
         requires:
           resources:
             - ankul_sample_node
         execution:
           onExecute:
             - echo hello_world!

       - name: test_bash_step_2
         type: bash
         setup:
           runtime:
             type: image
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!
             
       - name: test_bash_step_3
         type: bash
         setup:
           runtime:
             type: image
             auto:
               random: value
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!             
             
       - name: test_bash_step_4
         type: bash
         setup:
           runtime:
            type: image
            image:
              custom:
                name: drydock/u16all
                tag: master
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!             
                          
                         
       - name: invalid_language
         type: bash
         setup:
           runtime:
            type: image
            image:
              auto:
                language: its_invalid_lang
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!             
                                                   
       - name: invalid_version
         type: bash
         setup:
           runtime:
            type: image
            image:
              auto:
                language: nodeJs
                versions:
                  - 10.10.10
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!  
             
       - name: select_default_version
         type: bash
         setup:
           runtime:
            type: image
            image:
              auto:
                language: nodeJs
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!               
             
       - name: correct_version
         type: bash
         setup:
           runtime:
            type: image
            image:
              auto:
                language: nodeJs
                versions:
                  - 8.15.0
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!   
             
       - name: multiple_versions
         type: bash
         setup:
           runtime:
            type: image
            image:
              auto:
                language: nodeJs
                versions:
                  - 11.10.0
                  - 10.15.1
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!                
