resources:      
  - name: file
    type: file
    fileLocation: gs://bucket_name
    fileName: test.js
    configuration:
      integrationName: ankul_gcloud
    initialVersion:
      fileDtTm: "2019-01-06" 

pipelines:
  - name: ci_pipeline
    steps:
      - name: test_step
        type: bash
        requires:
          integrations:
            - ankul_gcloud
        execution:
          onExecute:
            - printenv
            - echo $int_ankul_gcloud_jsonKey
            - local jsonKey=$int_ankul_gcloud_jsonKey
            - echo $jsonKey
            - local projectId="$( echo "$jsonKey" | jq -r '.project_id' )"
            - touch key.json
            - echo "$jsonKey" > key.json
            - gcloud -q auth activate-service-account --key-file "key.json"
            - gcloud config set project "$projectId"
            - gsutil cp gs://shiptest/discussion.jpeg
            - ls
