resources:      
  - name: file
    type: file
    fileLocation: gs://bucket_name
    fileName: test.js
    configuration:
      integrationName: ankul_gcloud
    initialVersion:
      fileDtTm: "2019-01-06" 

pipelines:
  - name: ci_pipeline
    steps:
      - name: test_step
        type: bash
        requires:
          integrations:
            - ankul_gcloud
        execution:
          onExecute:
            - printenv
