resources:      
  - name: file
    type: file
    fileLocation: s3://strangers-beta/profiles
    fileName: 1.png
    configuration:
      integrationName: ankul_aws
    initialVersion:
      fileDtTm: "2019-01-06" 
      
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    initialVersion:
      sha: master     

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: bash
        requires:
          resources:
            - sample_node
        execution:
          onExecute:
            - printenv
