pipelines:
  - name: pipeline_default_auto_test
    steps:
       - name: test_bash_step
         type: bash
         execution:
           onExecute:
             - echo hello_world!

       - name: test_bash_step_2
         type: bash
         setup:
           runtime:
             type: image
         execution:
           onExecute:
             - echo hello_world!
             
       - name: test_bash_step_2
         type: bash
         setup:
           runtime:
             type: image
             auto:
               random: value
         execution:
           onExecute:
             - echo hello_world!             
             
