resources:
  - name: ankul_sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: test_pipeline_3
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - ankul_sample_node
        execution:
          onExecute:
            - echo "executing test bash step pipe_1_step_1..."
            
            
  - name: test_pipeline_2
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - ankul_sample_node
        execution:
          onExecute:
            - echo "executing test bash pipe_2_step_1..."  
