resources:      
#   - name: file
#     type: file
#     fileLocation: s3://strangers-beta/profiles
#     fileName: 1.png
#     configuration:
#       integrationName: ankul_aws
#     initialVersion:
#       fileDtTm: "2019-01-06" 
      
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    initialVersion:
      sha: master
      
  - name: state
    type: state
    initialVersion:
      KEY: value
      
  - name: state_2
    type: state
    initialVersion:
      KEY_2: value_2     

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step
        type: bash
        requires:
          resources:
            - state
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - printenv
        outputResources:
          - state
          - sample_node
          
      - name: step_2
        type: bash
        triggeredBy:
          resources:
            - sample_node
          steps:
            - step
        execution:
          onExecute:
            - printenv
        outputResources:
          - sample_node            
