resources:      
#   - name: file
#     type: file
#     fileLocation: s3://strangers-beta/profiles
#     fileName: 1.png
#     configuration:
#       integrationName: ankul_aws
#     initialVersion:
#       fileDtTm: "2019-01-06" 
      
#   - name: sample_node
#     type: gitRepo
#     repoPath: ankul-shippable/sample_node
#     configuration:
#       integrationName: ankul_github
#     initialVersion:
#       sha: master
      
  - name: internal_webhook
    type: webhook
    configuration:
      integrationName: int_webhook
    initialVersion:
      payload: "key=val key2=val2"     
      
  - name: internal_webhook_2
    type: webhook
    configuration:
      integrationName: int_webhook
    initialVersion:
      payload: "key=val key2=val2"  
      
  - name: external_webhook
    type: webhook
    configuration:
      integrationName: ext_webhook
    initialVersion:
      payload: "key=val key2=val2"     
      
  - name: external_webhook_2
    type: webhook
    configuration:
      integrationName: ext_webhook
    initialVersion:
      payload: "key=val key2=val2"        

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: bash
        requires:
          resources:
            - internal_webhook
            - external_webhook
        execution:
          onExecute:
            - printenv
        outputResources:
          - internal_webhook_2
          - external_webhook_2
