pipelines:
  - name: pipeline
    steps:
       - name: step_without_runtime
         type: bash
         execution:
           onExecute:
             - echo hello_world!
             - node -v

       - name: step_with_image
         type: bash
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0           
         execution:
           onExecute:
             - echo hello_world!
             - node -v
