resources:      
#   - name: file
#     type: file
#     fileLocation: s3://strangers-beta/profiles
#     fileName: 1.png
#     configuration:
#       integrationName: ankul_aws
#     initialVersion:
#       fileDtTm: "2019-01-06" 
      
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    initialVersion:
      sha: master
      
  - name: external_webhook
    type: webhook
    configuration:
      integrationName: ext_webhook
    initialVersion:
      payload: "key=val key2=val2"     
           

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: bash
        configuration:
          nodePool: ankul_u16_nodes
        setup:
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                versions:
                  - 8.15.0          
        requires:
          resources:
            - sample_node
        execution:
          onExecute:
            - printenv
            - node -v
