resources:
  - name: ankul_sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: ankul_test_pipeline
    setup:
      runtime: host
    steps:
      - name: ankul_test_bash_step
        type: bash
        setup:
          runtime: 
            type: host
        requires:
          integrations:
            - docker_registry
        triggeredBy:
          resources:
            - ankul_sample_node 
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            - docker login -u $int_docker_registry_username -p $int_docker_registry_password $int_docker_registry_url 
            - docker pull $int_docker_registry_url/docker-virtual/busybox:latest
