resources:
  - name: ankul_sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: github_int
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_default_auto_test
    steps:
       - name: test_bash_step
         type: bash
         requires:
           resources:
             - ankul_sample_node
         execution:
           onExecute:
             - echo hello_world!

       - name: test_bash_step_2
         type: bash
         setup:
           runtime:
             type: image
         requires:
           resources:
             - ankul_sample_node             
         execution:
           onExecute:
             - echo hello_world!
             
       - name: test_bash_step_2
         type: bash
         setup:
           runtime:
             type: image
             auto:
               random: value
         requires:
           resources:
             - ankul_sample_node               
         execution:
           onExecute:
             - echo hello_world!             
             
